### ISSUE TITLE
Fail to update buffet entry

### ISSUE THREAD

**Issue by Wayne-Sh** [cwfletcher/buffets#2]
For the test case "tb_buffet_update.v", the data stored in idx=1 is initialized as 32'hc089_5e81 and should be update to another value later. However the value is still the same after a update operation is performed.  ( Might be caused by the generated block in the dpram model, line 73~ line 91. )

**Comment by kartik-hegde** [comment]
Hi Wayne,

Good catch, the SEPARATE_PORTS flag was incorrectly used in `dpram.v`. Fixed it.

Let me know if it works for you.

**Comment by Wayne-Sh** [comment]
Dear Karthik
It works, thank you!
